modLoader="javafml"
loaderVersion="[4,)"
license="CC0-1.0"

[[mods]]
modId="ontime"
version="1.2.1"
displayName="OnTime"
description="Create custom timers with command execution capabilities.\n Perfect for minigames, events, or automated server tasks."
authors="MateoF24"

[[mixins]]
config="ontime.client.mixins.json"

[[dependencies.ontime]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.ontime]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.6)"
ordering="NONE"
side="BOTH"

[[dependencies.ontime]]
modId="cloth_config"
type="required"
versionRange="[15.0.140,)"
ordering="NONE"
side="BOTH"