modLoader="javafml"
loaderVersion="[47,)"
license="CC0-1.0"

[[mods]]
modId="ontime"
version="${version}"
displayName="OnTime"
description="Create custom timers with command execution capabilities. Perfect for minigames, events, or automated server tasks."
authors="MateoF24"

[[mixins]]
config="ontime.client.mixins.json"

[[dependencies.ontime]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.ontime]]
modId="minecraft"
mandatory=true
versionRange="1.20.1"
ordering="NONE"
side="BOTH"

[[dependencies.ontime]]
modId="cloth_config"
mandatory=true
versionRange="[11.0,)"
ordering="NONE"
side="BOTH"